app: minhaapp
containerArgs: []
cpuLimit: 500m
cpuRequest: 300m
environment: dev
image: ghcr.io/cse-labs/minhaapp:latest
ingressPrefix: /
livenessProbe: /healthz
memoryLimit: 128Mi
memoryRequest: 64Mi
namespace: minhaapp
nodePort: 30080
port: 8080
readinessProbe: /readyz
targets: []
template: pib-service
