{
 "title": "Application Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(HerAppDuration_count[1m]))"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(HerAppDuration_count[1m]))"
    }
   ]
  },
  {
   "title": "WebV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(WebVDuration_count[1m]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(HerAppDuration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(HerAppDuration_count{code != \"OK\"}[1m]))"
    }
   ]
  }
 ]
}